services:
  server:
    build:
      context: ./server
      target: dev
    ports:
      - "${PORT}:${PORT}"
    develop:
      watch:
        - path: ./server/package.json
          action: rebuild
        - path: ./server
          target: /app
          action: sync
